#ifndef _SOUNDS_H
#define _SOUNDS_H

//sound defs
#define SND_OFFSET 34
#define MONSTER_PAIN1 0

//witch stuff
#define WITCH_ALERT 1
#define WITCH_PAIN 2
#define WITCH_ATTACK 3

// mummy & frankenstein pain sounds
#define MONSTER_PAIN2 4
#define MONSTER_DEATH1 5
#define MONSTER_DEATH2 6
#define MONSTER_DEATH3 7

//player death is in the monster pain section
#define PLAYER_DEATH 8


//human stuff
#define HUMAN_PAIN1 9
#define HUMAN_PAIN2 10
#define HUMAN_PAIN3 11

#define WITCH_DEATH 12

#define HUMAN_ALERT1 13 
#define WITCH_ALERT1 14 
#define WITCH_ALERT2 15 
#define WITCH_ALERT3 16 
#define WITCH_ALERT4 17 
#define WITCH_ALERT5 18 
#define WITCH_ALERT6 19 

#define WITCH_DIE1 20

#define ENEMY_PISTOL_FIRE1 21
#define ENEMY_MAGIC_FIRE 22
#define ENEMY_PISTOL_FIRE2 23

#define PLAYER_MAGIC_WAND_FIRE 24
#define PLAAYER_REVOLVER_FIRE1 25
#define PLAAYER_REVOLVER_FIRE2 26


#define TURRET_FIRE 27

#define UNKNOWN_MAGIC 29
#define MAGIC_EXPLOSION 30

#define PLAYER_PLASMA_PISTOL_FIRE 31

#define BAT_ALERT 32
#define BAT_DIE 33

#define UNKNOWN_CRUNCH 34
#define FIRE_WOOSH1 35
#define FIRE_WOOSH2 36

#define HIDDEN_DOOR_OPEN 37
#define MAGIC_EXPLOSION1 39
#define MAGIC_EXPLOSION2 40

#define PLAYER_PICKUP_CRYSTAL_BALL 44
#define PLAYER_DRINK_POTION 45
#define PLAYER_PICKUP_UNKNOWN 46
#define PLAYER_PICKUP_KEY 47
#define PLAYER_UNLOCK_DOOR 48
#define PLAYER_PICKUP_MAGIC_EYE 49
#define PLAYER_PICKUP_PLASAMA 50

#define UNKNOWN_CLICK 51

#define HUMAN_SPOT1 52
#define HUMAN_SPOT2 53

#define MONSTER_SPOT1 54
#define MONSTER_SPOT2 55
#define MONSTER_SPOT3 56

#define UNKNOWN_JINGLE 57

#define MONSTER_GROWL 58
#define UNKNOWN_OOOH 59
#define UNKNOWN_SNAP 60
#define CREEK 61
#define UNKNOWN_WHEEZE 62

#define FRANKENSTEIN_ATTACK 63
#define UNKNOWN_EXPLOSION 64
#define UNKNOWN_SCRAPE 65
#define END_LEVEL_TELEPORT 66
#define RADIO_TUNE 67

#define UNKNOWN_WOOSH 68
#define UNKNOWN_BEEPBOOP 69
#define UNKNOWN_BOOP 70

#define GHOST_ALERT1 71
#define GHOST_DIE1 72

#define UNKNOWN_BANG2 73
#define UNKNOWN_BANG3 74
#define UNKNOWN_BANG4 75

#endif // !_SOUNDS_H
